### ISSUE TITLE
¿Pueda ser esta la idea del proyecto de ejemplo?

### ISSUE THREAD

**Issue by moche123** [himuraxkenji/didactic-winner#3]
Este pequeño ejemplo consiste en hacer una recolección de maestros pokemones así como de sus entrenadores, los pokemones extraídos de la api de pokemon y los maestros almacenados desde un archivo.JSON, entonces la idea será recolectarlos y mostrarlos en dos rutas; una para pokemones y otra para maestros. El ejemplo será sencillo con el objetivo de simplemente usar las herramientas vistas en la reunión

**Comment by himuraxkenji** [comment]
Por mi parte me parece perfecto 👍
